mv "10 Agriculture and the Need for Unity.rtf" "10_Agriculture_and_the_Need_for_Unity.rtf"		
mv "101 A Lahu Thanks a Shan Lady for Rice Without Curry.rtf"	"101_A_Lahu_Thanks_a_Shan_Lady_for_Rice_Without_Curry.rtf"		
mv "102 The Stupid Son-in-law Beats a Benevolent Bonze.rtf"	"102_The_Stupid_Son_in_law_Beats_a_Benevolent_Bonze.rtf"		
mv "103 The Ferocious Elephant.rtf"	"103_The_Ferocious_Elephant.rtf"		
mv "105 Monkey-meat in Broken Shan.rtf"	"105_Monkey_meat_in_Broken_Shan.rtf"		
mv "107a A Yellow Lahu Burns his Fingers.rtf"	"107a_A_Yellow_Lahu_Burns_his_Fingers.rtf"		
mv "107b The Tiger is Getting Ripe.rtf"	"107b_The_Tiger_is_Getting_Ripe.rtf"		
mv "107c A Black Lahu Rolls up his Pants to Have a Smoke.rtf"	"107c_A_Black_Lahu_Rolls_up_his_Pants_to_Have_a_Smoke.rtf"		
mv "107d A Sticky Problem That Parakeet Will Stick at Nothing.rtf"	"107d_A_Sticky_Problem_That_Parakeet_Will_Stick_at_Nothing.rtf"		
mv "108 Stupid Son in Law the Red Ants and the rice packet.rtf"	"108_Stupid_Son_in_Law_the_Red_Ants_and_the_rice_packet.rtf"		
mv "110 The Empty Coconuts- the Lahu and the Shan Traders.rtf"	"110_The_Empty_Coconuts_the_Lahu_and_the_Shan_Traders.rtf"		
mv "115 Dividing a slaughtered pig fairly.rtf"	"115_Dividing_a_slaughtered_pig_fairly.rtf"		
mv "116 A Liar Kills a Bear and a Mountain Goat.rtf"	"116_A_Liar_Kills_a_Bear_and_a_Mountain_Goat.rtf"		
mv "117 Trapping a Deer in a Tree.rtf"	"117_Trapping_a_Deer_in_a_Tree.rtf"		
mv "118 A Lahu Sells Wasp Larvae to a Shan.rtf"	"118_A_Lahu_Sells_Wasp_Larvae_to_a_Shan.rtf"		
mv "119 A Lahu Gives A Shan a Good Cursing.rtf"	"119_A_Lahu_Gives_A_Shan_a_Good_Cursing.rtf"		
mv "12 Sermon—The Widow's Mites.rtf"	"12_Sermon_The_Widow_s_Mites.rtf"		
mv "120 Discussion of Lahu Customs.rtf"	"120_Discussion_of_Lahu_Customs.rtf"		
mv "120 The Lazy Men and the Princess.rtf"	"120_The_Lazy_Men_and_the_Princess.rtf"		
mv "121 A Smoker and a Non-Smoker Dispute a Pipe.rtf"	"121_A_Smoker_and_a_Non_Smoker_Dispute_a_Pipe.rtf"		
mv "126 Playing Ball at New-Rice Festival.rtf"	"126_Playing_Ball_at_New_Rice_Festival.rtf"		
mv "128 The Widow and her Head-child.rtf"	"128_The_Widow_and_her_Head_child.rtf"		
mv "129 The Boastful Cock and the Hawk.rtf"	"129_The_Boastful_Cock_and_the_Hawk.rtf"		
mv "13 Sermon—The Widow's Mites.rtf"	"13_Sermon_The_Widow_s_Mites.rtf"		
mv "130 Hunting crabs with granny.rtf"	"130_Hunting_crabs_with_granny.rtf"		
mv "131 Struggling to Survive with Lazy Husbands.rtf"	"131_Struggling_to_Survive_with_Lazy_Husbands.rtf"		
mv "133 The Snake and the Widow's Daughters.rtf"	"133_The_Snake_and_the_Widow_s_Daughters.rtf"		
mv "135 Sermon (Ca-bo).rtf"	"135_Sermon_Ca_bo_.rtf"		
mv "137 Man's primeval gourd goes missing and god looks for it.rtf"	"137_Man_s_primeval_gourd_goes_missing_and_god_looks_for_it.rtf"		
mv "139 God struggles with the Titan.rtf"	"139_God_struggles_with_the_Titan.rtf"		
mv "14 Sermon—The Widow's Mites.rtf"	"14_Sermon_The_Widow_s_Mites.rtf"		
mv "15 Lectures on Medicine.rtf"	"15_Lectures_on_Medicine.rtf"		
mv "157 I'm feeling sad.rtf"	"157_I_m_feeling_sad.rtf"		
mv "165 Conversation between Paul, Cabo, and Thu-yi.rtf"	"165_Conversation_between_Paul_Cabo_and_Thu_yi.rtf"		
mv "165 The Orphan's Riddes and the Traders.rtf"	"165_The_Orphan_s_Riddes_and_the_Traders.rtf"		
mv "166_the_Wicked_Older_Brother_and_the_good_Younger_Brother.rtf"	"166_the_Wicked_Older_Brother_and_the_good_Younger_Brother.rtf"		
mv "17 Spirits that Bite and Those that Don't.rtf"	"17_Spirits_that_Bite_and_Those_that_Don_t.rtf"		
mv "19 Song- We are Rising Up.rtf"	"19_Song_We_are_Rising_Up.rtf"		
mv "20 How We Came from Burma.rtf"	"20_How_We_Came_from_Burma.rtf"		
mv "23 Candid conversation.rtf"	"23_Candid_conversation.rtf"		
mv "24 Building a house.rtf"	"24_Building_a_house.rtf"		
mv "25 The women go fishing.rtf"	"25_The_women_go_fishing.rtf"		
mv "27 In Unity there is Strength.rtf"	"27_In_Unity_there_is_Strength.rtf"		
mv "28 The blind man and the cripple.rtf"	"28_The_blind_man_and_the_cripple.rtf"		
mv "29 The potter and the laundryman.rtf"	"29_The_potter_and_the_laundryman.rtf"		
mv "30 The blind men and the elephant.rtf"	"30_The_blind_men_and_the_elephant.rtf"		
mv "31 Marriage and Divorce.rtf"	"31_Marriage_and_Divorce.rtf"		
mv "32 How woman got her clitoris.rtf"	"32_How_woman_got_her_clitoris.rtf"		
mv "33 The_Trader_and_the_Widow's_Balls.rtf"	"33_The_Trader_and_the_Widow_s_Balls.rtf"		
mv "34 Farting and playing tag.rtf"	"34_Farting_and_playing_tag.rtf"		
mv "35 In Unity There is Strength.rtf"	"35_In_Unity_There_is_Strength.rtf"		
mv "37 Song of Reconciliation of the Brother and Sister.rtf"	"37_Song_of_Reconciliation_of_the_Brother_and_Sister.rtf"		
mv "38 The Trickster and the Traders.rtf"	"38_The_Trickster_and_the_Traders.rtf"		
mv "39 The Trickster's Spear and the Merchants.rtf"	"39_The_Trickster_s_Spear_and_the_Merchants.rtf"		
mv "3x The Trickster and the Village Women.rtf"	"3x_The_Trickster_and_the_Village_Women.rtf"		
mv "46a Welcome to Shatodo Village.rtf"	"46a_Welcome_to_Shatodo_Village.rtf"		
mv "48 Edifying thoughts on God, parents and village.rtf"	"48_Edifying_thoughts_on_God_parents_and_village.rtf"		
mv "49 Granny gets smeared with mud.rtf"	"49_Granny_gets_smeared_with_mud.rtf"		
mv "52 Hunting_jungle_fowl.rtf"	"52_Hunting_jungle_fowl.rtf"		
mv "53 Monkey Hunting.rtf"	"53_Monkey_Hunting.rtf"		
mv "55 The Dhole and the Tiger.rtf"	"55_The_Dhole_and_the_Tiger.rtf"		
mv "57 The General Conference of Christian Lahu.rtf"	"57_The_General_Conference_of_Christian_Lahu.rtf"		
mv "59 Lecture for Lahu Christian Youth.rtf"	"59_Lecture_for_Lahu_Christian_Youth.rtf"		
mv "60 The six stupid men and the gophers.rtf"	"60_The_six_stupid_men_and_the_gophers.rtf"		
mv "61 The orphan and the tigers.rtf"	"61_The_orphan_and_the_tigers.rtf"		
mv "64 Welcome to the village.rtf"	"64_Welcome_to_the_village.rtf"		
mv "65 Visiting the village's fields.rtf"	"65_Visiting_the_village_s_fields.rtf"		
mv "66 Candid Conversation- Working up to being recorded.rtf"	"66_Candid_Conversation_Working_up_to_being_recorded.rtf"		
mv "67 A Day Hunting and Talking.rtf"	"67_A_Day_Hunting_and_Talking.rtf"		
mv "68 The Rabbit and the Tiger.rtf"	"68_The_Rabbit_and_the_Tiger.rtf"		
mv "69 Picking tea.rtf"	"69_Picking_tea.rtf"		
mv "70 Wooing the Maidens.rtf"	"70_Wooing_the_Maidens.rtf"		
mv "78 The Government Offers Us New Lands.rtf"	"78_The_Government_Offers_Us_New_Lands.rtf"		
mv "8 A Lahu Hunting Expedition.rtf"	"8_A_Lahu_Hunting_Expedition.rtf"		
mv "80 Christmas, New Year’s, and the New Rice Festival.rtf"	"80_Christmas_New_Year_s_and_the_New_Rice_Festival.rtf"		
mv "84 The Buffalo-Bugger and the Rabbit Hunters.rtf"	"84_The_Buffalo_Bugger_and_the_Rabbit_Hunters.rtf"		
mv "85 Courting Badinage.rtf"	"85_Courting_Badinage.rtf"		
mv "85 God's Word and the Recent Disharmony in our Village.rtf"	"85_God_s_Word_and_the_Recent_Disharmony_in_our_Village.rtf"		
mv "86 Headman's communication.rtf"	"86_Headman_s_communication.rtf"		
mv "86 The Three Lazy Men and the Princess.rtf"	"86_The_Three_Lazy_Men_and_the_Princess.rtf"		
mv "86b [continued from #85] Sermon- the recent disharmony in our village.rtf"	 "86b_continued_from_85_Sermon_the_recent_disharmony_in_our_village.rtf"	
mv "88 Building an Airstrip.rtf"	"88_Building_an_Airstrip.rtf"		
mv "9 Agriculture and the Need for Unity.rtf"	"9_Agriculture_and_the_Need_for_Unity.rtf"		
mv "90 Laying_up_riches_in_heaven.rtf"	"90_Laying_up_riches_in_heaven.rtf"		
mv "90 Proverbs.rtf"	"90_Proverbs.rtf"		
mv "92 The_trickster_and_the_old_bonze.rtf"	"92_The_trickster_and_the_old_bonze.rtf"		
mv "93 Changeless Jesus.rtf"	"93_Changeless_Jesus.rtf"		
mv "94 The Fingerless Lord.rtf"	"94_The_Fingerless_Lord.rtf"		
mv "95 The Trickster with the Warbling Pecker.rtf"	"95_The_Trickster_with_the_Warbling_Pecker.rtf"		
mv "96 The Little Crabs Who Walked Zig-zag.rtf"	"96_The_Little_Crabs_Who_Walked_Zig_zag.rtf"		
mv "97 The Lion and the Frog.rtf"	"97_The_Lion_and_the_Frog.rtf"		
mv "98 Resurrection of a Barking Deer and Fulfillment of a Prophecy.rtf"	"98_Resurrection_of_a_Barking_Deer_and_Fulfillment_of_a_Prophecy.rtf"